### ISSUE TITLE
[authentication-with-auth0-and-apollo] Deprecated react-native-lock Prevents Running Authentication with Auth0 and Apollo

### ISSUE THREAD

**Issue by rts-rob** [graphql-boilerplates/react-native-fullstack-graphql#10]
The npm package `react-native-lock` has been deprecated in favor of `react-native-auth0`. In practice, this is a breaking change, as the old API cannot be used with newly created clients. This means that new users working through the examples are unable to get the "Authentication with Auth0 and Apollo" example to function.

Request replacement of `react-native-lock` with `react-native-auth0` following guidelines from the [Auth0 React-Native repo](https://github.com/auth0/react-native-auth0).

**Comment by ylac** [comment]
Yes this is very much needed.

**Comment by DevanB** [comment]
Closing this issue as this project has pivoted into an opinionated boilerplate. The advanced boilerplate will include authentication through Prisma.
