### ISSUE TITLE
authentication-with-expo-and-auth0 example is too old

### ISSUE THREAD

**Issue by j2l** [graphql-boilerplates/react-native-fullstack-graphql#12]
I followed all the steps and stumbled on ` import Exponent from 'exponent'`
I supected it will fail and it did: 
`Unhandled Promise Rejection (id:0): Invalid token specified`

Additionally, note that [auth0 decommissioned legacy API and Expo example is broken too](https://github.com/expo/auth0-example/issues/6).

May be it's time to make an example using GraphCool email/password with Expo 20.0.0 :)

**Comment by DevanB** [comment]
Closing this issue as this project has pivoted into an opinionated boilerplate. The advanced boilerplate will include authentication through Prisma.
