### ISSUE TITLE
checkUri causes issue

### ISSUE THREAD

**Issue by nikolasburk** [graphql-boilerplates/react-native-fullstack-graphql#2]
The `checkUri(client.networkInterface)` call in `root.js` gives the following error:

![simulator screen shot 24 mar 2017 12 07 51](https://cloud.githubusercontent.com/assets/4058327/24291759/949aec1a-108a-11e7-97b0-e83f970618bf.png)

Commenting it out makes the app start properly.

**Comment by marktani** [comment]
What's the url you provided?

**Comment by nikolasburk** [comment]
`https://api.graph.cool/simple/v1/whipdart-antelope-513` (generated with `graphql-up`)

**Comment by marktani** [comment]
Ah I see, the current implementation assumes that the part after the last slash is a cuid.

**Comment by DevanB** [comment]
Closing this issue as this is no longer an issue due to project refactor.
