### ISSUE TITLE
[authentication-with-auth0-and-apollo] Cannot read property 'init' of undefined

### ISSUE THREAD

**Issue by dk0r** [graphql-boilerplates/react-native-fullstack-graphql#7]
Receiving following error from the [authentication-with-auth0-and-apollo](https://github.com/graphcool-examples/react-native-graphql/tree/master/authentication-with-auth0-and-apollo) example:  
- [**Cannot read property 'init' of undefined**](http://i.imgur.com/mkCyHmY.png)

**Versions**:
- react-native@0.44.2
- Android studio [@2.3.2](http://i.imgur.com/lIAp2ih.png) 
- A virtual android device @ [API 23](http://i.imgur.com/SsIJzLl.png):

**Steps to reproduce**: 
- Unzip the [authentication-with-auth0-and-apollo](https://github.com/graphcool-examples/react-native-graphql/tree/master/authentication-with-auth0-and-apollo) example
- Install deps by doing `yarn` in main directory
- Set `AUTH0_CLIENT_ID` and `AUTH0_DOMAIN` as described [here](https://github.com/graphcool-examples/react-native-graphql/tree/master/authentication-with-auth0-and-apollo#4-configure-auth0-credentials)
- Implement fix described [here](https://github.com/graphcool-examples/react-native-graphql/issues/6) (if receiving **transformResourcesWithMergeJavaResForDebug** error)
- After example builds and runs on android, then click `login` as shown [here] (http://i.imgur.com/8e2tPxq.png) 
- Incur the following error: [**Cannot read property 'init' of undefined**](http://i.imgur.com/mkCyHmY.png)

**Expected behavior**: 
- App should switch to a login page view.

**Solution**:
- Error is resolved by following Auth0's [manual configuration instructions](https://github.com/auth0/react-native-lock#manually-1) (paraphrased below):

1. Add the following import to **.../android/app/src/main/java/com/auth0example/MainApplication.java**:
`import com.auth0.lock.react.LockReactPackage;`

2. In the same **MainApplication.java** file, add the `LockReactPackage()` module as shown below: 
```
    /**
     * A list of packages used by the app. If the app uses additional views
     * or modules besides the default ones, add more packages here.
     */
    @Override
    protected List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList(
            new MainReactPackage(),
            //Other RN modules
            new LockReactPackage()
        );
    }
```

3. In the **.../android/app/src/main/AndroidManifest.xml** add the following inside `<application>` tag:
```
<!--Auth0 Lock-->
<activity
  android:name="com.auth0.lock.LockActivity"
  android:theme="@style/Lock.Theme"
  android:screenOrientation="portrait"
  android:launchMode="singleTask">
</activity>
<!--Auth0 Lock End-->
<!--Auth0 Lock Embedded WebView-->
<activity
    android:name="com.auth0.identity.web.WebViewActivity"
    android:theme="@style/Lock.Theme">
</activity>
<!--Auth0 Lock Embedded WebView End-->
<!--Auth0 Lock Passwordless-->
<activity
    android:name="com.auth0.lock.passwordless.LockPasswordlessActivity"
    android:theme="@style/Lock.Theme"
    android:screenOrientation="portrait"
    android:launchMode="singleTask">
</activity>
<activity
    android:name="com.auth0.lock.passwordless.CountryCodeActivity"
    android:theme="@style/Lock.Theme">
</activity>
<!--Auth0 Lock Passwordless End-->
```
**Note**:
-  This issue is likely occurring on all of Graphcool's [Auth0 based](https://github.com/graphcool-examples/react-native-graphql) react-native examples.
- See Auth0's [manual configuration instructions](https://github.com/auth0/react-native-lock#manually-1) for details on correcting this and other errors you will incur with graphcool's react-native auth0 examples.

**Comment by DevanB** [comment]
Closing this issue as this project has pivoted into an opinionated boilerplate. The advanced boilerplate will include authentication through Prisma.
